In [11]:
from sklearn.datasets import load_diabetes


In [12]:
import pandas as pd
import numpy as np


In [13]:
df=load_diabetes()
df

{'data': array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
          0.01990749, -0.01764613],
        [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
         -0.06833155, -0.09220405],
        [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
          0.00286131, -0.02593034],
        ...,
        [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
         -0.04688253,  0.01549073],
        [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
          0.04452873, -0.02593034],
        [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
         -0.00422151,  0.00306441]]),
 'target': array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
         69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
         68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
         87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
        259.,  53., 190., 142.,  75., 142., 155., 225.,  59

In [14]:
dataset=pd.DataFrame(df['data'])

In [15]:
dataset

0         1         2         3         4         5         6  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

            7         8         9  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [16]:
dataset.columns=df['feature_names']

In [17]:
dataset

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [18]:
dataset['price']=df['target']
dataset

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  price  
0   -0.002592  0.019907 -0.017646  151.0  
1   -0.039493 -0.068332 -0.092204   75.0  
2   -0.002592  0.002861 -0.025930  141.0  
3    0.034309  0.022688 -0.009362  206.0  
4   -0.002592 -0.031988 -0.046641  135.0  
..        ...       ...       ...    ...  
437 -0.002592  0.031193  0.007207  178.0  
438  0.034309 -0.018114  0.044485  104.0  
439 -0.011080 -0.046883  0.015491  132.0  
440  0.026560  0.044529 -0.025930  220.0  
441 -0.039493 -0.004222  0.003064   57.0  

[442 rows x 11 columns]

In [19]:
## converting dataset into dependent and independent features
x=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

In [20]:
x

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019907 -0.017646  
1   -0.039493 -0.068332 -0.092204  
2   -0.002592  0.002861 -0.025930  
3    0.034309  0.022688 -0.009362  
4   -0.002592 -0.031988 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018114  0.044485  
439 -0.011080 -0.046883  0.015491  
440  0.026560  0.044529 -0.025930  
441 -0.039493 -0.004222  0.003064  

[442 rows x 10 columns]

In [21]:
y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...  
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: price, Length: 442, dtype: float64

In [22]:
dataset.isnull()

age    sex    bmi     bp     s1     s2     s3     s4     s5     s6  \
0    False  False  False  False  False  False  False  False  False  False   
1    False  False  False  False  False  False  False  False  False  False   
2    False  False  False  False  False  False  False  False  False  False   
3    False  False  False  False  False  False  False  False  False  False   
4    False  False  False  False  False  False  False  False  False  False   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
437  False  False  False  False  False  False  False  False  False  False   
438  False  False  False  False  False  False  False  False  False  False   
439  False  False  False  False  False  False  False  False  False  False   
440  False  False  False  False  False  False  False  False  False  False   
441  False  False  False  False  False  False  False  False  False  False   

     price  
0    False  
1    False  
2    False  
3    False  
4    False  
..     ...  
437  False  
438  False  
439  False  
440  False  
441  False  

[442 rows x 11 columns]

In [23]:
ds=dataset.dropna()
ds

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017293 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081413  0.083740  0.027809  0.173816   

           s4        s5        s6  price  
0   -0.002592  0.019907 -0.017646  151.0  
1   -0.039493 -0.068332 -0.092204   75.0  
2   -0.002592  0.002861 -0.025930  141.0  
3    0.034309  0.022688 -0.009362  206.0  
4   -0.002592 -0.031988 -0.046641  135.0  
..        ...       ...       ...    ...  
437 -0.002592  0.031193  0.007207  178.0  
438  0.034309 -0.018114  0.044485  104.0  
439 -0.011080 -0.046883  0.015491  132.0  
440  0.026560  0.044529 -0.025930  220.0  
441 -0.039493 -0.004222  0.003064   57.0  

[442 rows x 11 columns]

In [24]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [25]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
lin_reg=model.fit(x_train,y_train)

y_pred=lin_reg.predict(x_test)
y_pred

array([139.08778555, 184.73870057, 131.6095325 , 284.90943025,
       122.64913588,  90.11610362, 257.30792581, 179.16210464,
        81.60189138, 109.90804773,  95.93670644, 168.86654734,
        61.06600627, 202.54476202,  95.6675196 , 129.52099062,
       211.39746771, 247.04551598, 201.84581418, 218.29511044,
       204.74433872,  89.24690391,  65.74005798, 189.76527361,
       157.01099642, 164.09010146, 195.89413327, 184.44675625,
        47.17814271, 108.36041121, 175.22288093,  89.70805135,
       127.68067335, 181.57571652, 168.40472388, 195.63732017,
       120.01792029, 115.51275723, 139.78494568,  59.50390312,
        67.14800417, 108.66524288, 170.2500668 , 145.34009866,
       167.87220501,  65.4127031 ,  71.23262502, 105.93318662,
        55.55240836, 165.26240902, 155.67111483,  66.95625003,
       110.93961535, 106.10785529, 179.34817487, 163.38869479,
        90.80940237, 212.75615079, 120.74246556,  63.60891537,
       185.25037795, 204.70429839, 140.92051154, 105.09

In [26]:
from sklearn.metrics import r2_score
score1=r2_score(y_pred,y_test)
score1

0.1104203175335221

In [27]:
from sklearn.model_selection import cross_val_score
mse=cross_val_score(lin_reg,x_train,y_train)
mse

array([0.48728349, 0.35896633, 0.57390193, 0.55645232, 0.28321181])

In [28]:
np.mean(mse)

0.4519631771331894

In [29]:
## Ridge
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
ridge=Ridge()
params={'alpha':[1e-15,1e-9,1e-1,4,8,14,48,72,93,100]}
ridge_regressor=GridSearchCV(ridge,params,cv=10)
ridge_regressor.fit(x,y)

GridSearchCV(cv=10, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-09, 0.1, 4, 8, 14, 48, 72, 93,
                                   100]})

In [30]:
y_pred=ridge_regressor.predict(x_test)
y_pred

array([148.56392894, 172.8404014 , 148.99175113, 283.59282557,
       126.22917133, 103.99843289, 250.46997561, 197.07777467,
        96.13244673, 119.04860106, 103.07991836, 158.3248106 ,
        68.75517753, 206.40529282, 106.10549938, 132.48027397,
       222.09581543, 239.09945493, 187.15598556, 209.05780801,
       207.19662184,  93.18809689,  78.72949072, 187.21837366,
       156.82469516, 158.62418484, 182.85845494, 170.34872329,
        57.66652185, 118.11838002, 175.6219868 ,  98.22198876,
       136.59428195, 179.53780302, 171.63506905, 196.4455182 ,
       128.40101242, 126.10978453, 150.21857774,  64.44126208,
        81.73723239, 109.19755947, 156.00379636, 148.2318916 ,
       179.02810931,  70.61863165,  85.66547147, 107.14449112,
        62.89376284, 161.92458118, 150.58710797,  73.8250393 ,
       110.22628663, 110.78163668, 174.22826418, 154.2595461 ,
       102.28939396, 199.84609431, 121.05332264,  75.55583996,
       187.65286905, 198.92613475, 140.96209793, 110.77

In [31]:
print(ridge_regressor.best_params_)
print(ridge_regressor.best_score_)

{'alpha': 0.1}
0.46332219117960366


In [32]:
## lasso

from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
model=Lasso()
params={'alpha':[1e-12,1e-4,1e-2,34,25,56,78,90,100,110]}
lasso_regressor=GridSearchCV(model,params,cv=10)


In [33]:
lasso_regressor.fit(x_train,y_train)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.847e+05, tolerance: 1.596e+02
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.732e+05, tolerance: 1.604e+02
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.797e+05, tolerance: 1.613e

GridSearchCV(cv=10, estimator=Lasso(),
             param_grid={'alpha': [1e-12, 0.0001, 0.01, 34, 25, 56, 78, 90, 100,
                                   110]})

In [42]:

y_p=lasso_regressor.predict(x_test)

In [44]:
y_p

array([139.04773253, 184.65046976, 135.62409673, 284.57375466,
       121.34834543,  91.40734034, 257.31939034, 183.45547372,
        79.03120461, 112.35010362,  96.63617054, 163.63948639,
        67.16861762, 201.96508748,  96.07454239, 131.5060318 ,
       213.49491405, 244.56384002, 201.57504728, 215.86421255,
       204.44306336,  88.77158136,  67.94386354, 189.23275031,
       158.18410936, 165.27223676, 196.21815081, 181.18727674,
        49.18504862, 109.8074938 , 178.18378456,  92.72970552,
       127.57397196, 178.9961812 , 167.35741572, 196.91079543,
       119.4125595 , 114.98437376, 138.67290042,  60.62996249,
        69.77769512, 109.57062556, 166.98510762, 141.60787982,
       169.83936323,  68.09085736,  75.89712072, 102.51643884,
        59.37678284, 161.39236125, 158.38545714,  68.24677141,
       115.9640847 , 105.73113732, 175.10518137, 166.16251485,
        91.18776724, 210.64096411, 119.40626575,  60.7205948 ,
       182.84220742, 201.90448051, 142.8766986 , 105.93

In [45]:
from sklearn.metrics import r2_score
r2score1=r2_score(y_p,y_test)

In [46]:
r2score1

0.07796676321872487

In [47]:
from sklearn.model_selection import cross_val_score


In [48]:
mse=cross_val_score(lasso_regressor,x_train,y_train)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.004e+05, tolerance: 1.318e+02
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.978e+05, tolerance: 1.247e+02
  model = cd_fast.enet_coordinate_descent(
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.751e+05, tolerance: 1.294e

In [40]:
mse

array([0.48633245, 0.35733725, 0.56967794, 0.55471764, 0.28832575])

In [41]:
np.mean(mse)

0.4512782062846548